// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuotesFinal.Models;

namespace QuotesFinal.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("QuotesFinal.Models.QuoteResponse", b =>
                {
                    b.Property<int>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Citation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.HasKey("QuoteId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            QuoteId = 1,
                            Author = "Kanye West",
                            Citation = "Twitter",
                            Date = "Jan 16, 2018",
                            Quote = "You can't look at a glass half full or empty if it's overflowing",
                            Subject = "Perspective"
                        },
                        new
                        {
                            QuoteId = 2,
                            Author = "Elon Musk",
                            Citation = "Twitter",
                            Date = "Apr 9, 2022",
                            Quote = "69.420% of statistics are false",
                            Subject = "Satire"
                        },
                        new
                        {
                            QuoteId = 3,
                            Author = "Abraham Lincoln",
                            Citation = "Gettysburg Address",
                            Date = "Nov 19, 1863",
                            Quote = "Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal.",
                            Subject = "History"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
